# EDA with Pandas & sqlalchemy
How to query a database and perform edas with pandas + sql.

In [1]:
!pip install sqlalchemy psycopg2-binary Pandas

Requirement already satisfied: sqlalchemy in /opt/conda/lib/python3.9/site-packages (1.4.29)
Requirement already satisfied: psycopg2-binary in /opt/conda/lib/python3.9/site-packages (2.9.3)
Requirement already satisfied: Pandas in /opt/conda/lib/python3.9/site-packages (1.3.5)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.9/site-packages (from sqlalchemy) (1.1.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.9/site-packages (from Pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.9/site-packages (from Pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.9/site-packages (from Pandas) (1.20.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil>=2.7.3->Pandas) (1.16.0)

In [2]:
from sqlalchemy.engine.url import URL
from sqlalchemy import create_engine, MetaData, Table, dialects
import pandas as pd
postgres_db = {'drivername': 'postgresql',
               'username': 'postgres',
               'password': 'postgres',
               'host': '172.17.0.1', # alternatively, 127.0.0.1/localhost if running standalone
               'port': 5432,
               'database': 'postgres'
               }
pgURL = URL(**postgres_db)
engine = create_engine(pgURL)
conn = engine.connect()

/tmp/ipykernel_135/1390914322.py:11: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
  pgURL = URL(**postgres_db)

In [3]:
query = """
SELECT * FROM information_schema.tables
"""
df = pd.read_sql(query, conn)
df

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,postgres,pg_catalog,pg_statistic,BASE TABLE,None,None,None,None,None,YES,NO,None
1,postgres,pg_catalog,pg_type,BASE TABLE,None,None,None,None,None,YES,NO,None
2,postgres,pg_catalog,pg_foreign_table,BASE TABLE,None,None,None,None,None,YES,NO,None
3,postgres,pg_catalog,pg_authid,BASE TABLE,None,None,None,None,None,YES,NO,None
4,postgres,pg_catalog,pg_shadow,VIEW,None,None,None,None,None,NO,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...
198,postgres,information_schema,foreign_servers,VIEW,None,None,None,None,None,NO,NO,None
199,postgres,information_schema,_pg_foreign_tables,VIEW,None,None,None,None,None,NO,NO,None
200,postgres,information_schema,user_mapping_options,VIEW,None,None,None,None,None,NO,NO,None
201,postgres,information_schema,foreign_tables,VIEW,None,None,None,None,None,NO,NO,None
202,postgres,information_schema,_pg_user_mappings,VIEW,None,None,None,None,None,NO,NO,None

In [4]:
query = """
SELECT * FROM information_schema.tables
WHERE table_schema = 'pg_catalog'
"""
df_2 = pd.read_sql(query, conn)
df_2

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,postgres,pg_catalog,pg_statistic,BASE TABLE,None,None,None,None,None,YES,NO,None
1,postgres,pg_catalog,pg_type,BASE TABLE,None,None,None,None,None,YES,NO,None
2,postgres,pg_catalog,pg_foreign_table,BASE TABLE,None,None,None,None,None,YES,NO,None
3,postgres,pg_catalog,pg_authid,BASE TABLE,None,None,None,None,None,YES,NO,None
4,postgres,pg_catalog,pg_shadow,VIEW,None,None,None,None,None,NO,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...
129,postgres,pg_catalog,pg_stat_database,VIEW,None,None,None,None,None,NO,NO,None
130,postgres,pg_catalog,pg_stat_database_conflicts,VIEW,None,None,None,None,None,YES,NO,None
131,postgres,pg_catalog,pg_stat_user_functions,VIEW,None,None,None,None,None,NO,NO,None
132,postgres,pg_catalog,pg_user_mappings,VIEW,None,None,None,None,None,NO,NO,None
133,postgres,pg_catalog,pg_largeobject,BASE TABLE,None,None,None,None,None,YES,NO,None

In [5]:
conn.close()